---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "avatarcreator"
  namespace: "default"
  labels:
    app: "avatarcreator"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "avatarcreator"
  template:
    metadata:
      labels:
        app: "avatarcreator"
    spec:
      containers:
      - name: "springboot-microservices"
        image: "gcr.io/<GCP_PROJECT_NAME>/github.com/bbideep/springboot-microservices:$COMMIT_SHA"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "avatarcreator-hpa"
  namespace: "default"
  labels:
    app: "avatarcreator"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "avatarcreator"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "avatarcreator-service"
  namespace: "default"
  labels:
    app: "avatarcreator"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "avatarcreator"
  type: "LoadBalancer"
  loadBalancerIP: "{LOADBALANCER_IP}"
