version: 2
jobs:
  build:
    
    working_directory: ~/avatar_id_creator/

    docker:
      - image: gradle:5.0.0-jdk11-slim

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: >
          chown -R gradle ~/avatar_id_creator/ 
          && cd ~/avatar_id_creator/avatar_id_creator/ 
          && /usr/bin/gradle build --stacktrace 
#          && ls -la ~/avatar_id_creator/ && ls -la ~/avatar_id_creator/avatar_id_creator
#          && ls -l build/ && ls -l build/libs && ls -l build/resources
