version: 2
jobs:
  build:
    
    working_directory: ~/avatar_id_creator/

    docker:
      - image: gradle:5.0.0-jdk11-slim

    steps:

      - checkout

      - run: ls -la /home/gradle && ls -la /home/gradle/.gradle && /home/gradle/.gradle/gradle build && ls -la . && ls -la ~/avatar_id_creator/avatar_id_creator/ && echo $PATH
      
