version: 2
jobs:
  build:
    
    working_directory: ~/avatar_id_creator/

    docker:
      - image: gradle:5.0.0-jdk11-slim
      #- image: gradle:4.2.1-jdk8-alpine
      #- image: circleci/openjdk:8-jdk
      #- image: circleci/jdk8:0.1.1

    steps:
      - checkout
      - run: ls -la && chown -R gradle ~/avatar_id_creator/ && ./gradlew build --stacktrace
